package cloud.query;

public interface BuyMonthlyQuery {
	String CHECKBUY = "SELECT * FROM BUY_MONTHLY_TICKET WHERE LICENCE_PLATE = ?1 AND MONTH(BUY_DATE) = ?2 AND YEAR(BUY_DATE) = ?3";
	
	String TICKET = "SELECT TYPE_TICKET FROM REGISTER_MONTHLY_TICKET WHERE LICENCE_PLATE = ?1";
	
	String GETSTAMP = "SELECT * FROM BUY_MONTHLY_TICKET WHERE LICENCE_PLATE = ?1 AND MONTH(BUY_DATE) = ?2 AND YEAR(BUY_DATE) = ?3";
	
}
