package cloud.query;

public interface ParkingQuery {

	String GETSLOT = "SELECT SLOT FROM PARKING WHERE ID=?";
	
	String COUNTVEHICLE = "SELECT COUNT(CHECK_IN.ID) AS TOTAL FROM CHECK_IN INNER JOIN PARKING ON CHECK_IN.PARKING_ID=PARKING.ID WHERE STATUS = ?1 AND CHECK_IN.PARKING_ID = ?2";
}
